### ISSUE TITLE
possible to show and hide the panel with a hotkey?

### ISSUE THREAD

**Issue by nrser** [Seicun/atom-watcher#2]
hey, just installed this plugin and checking it out, seems pretty sweet - thanks.

wondering if there is a way to show/hide the watcher panel with a hotkey? i'd like to be able to flip it open and closed with the keyboard like a console visor.

**Comment by maevic** [comment]
Hi, thanks for your suggestion. I just added a shortcut to toggle the watcher panel. The default shortcut is ctrl-alt-q.

**Comment by nrser** [comment]
awesome, i'll check it out. thanks!
